title: L300 Extending M365
description: 
theme: just-the-docs

aux_links:
  "L300 Extending M365": 
    - "https://github.com/microsoft/Techworkshop-L300-Extending-M365"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: important
    color: blue
  new:
    title: new
    color: green
  note:
    title: note 
    color: purple
  warning:
    title: warning
    color: red
